#!/bin/sh

if [ -f /etc/init/dnsovertcp ]; then
    /etc/init/dnsovertcp stop
fi

python setup.py bdist_egg
easy_install -q dist/dnsovertcp-*.egg
/bin/cp -f bin/dns-overtcp /usr/local/bin
/bin/cp -f service/dnsovertcp /etc/init.d
chmod +x /usr/local/bin/dns-overtcp
chmod +x /etc/init.d/dnsovertcp

echo "dnsovertcp installed successfully"
